republish:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: saulach
depublish_bridge:
  fields:
    bridge_device:
      required: true
      selector:
        device:
          integration: saulach
